name: Build and Deploy
on:
  push:
    branches: web
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - name: Config
        run: flutter config --enable-web

      - name: Update
        run: flutter pub get

      - name: Build ðŸ”§
        run: flutter build web --release

      - name: CNAME
        run: echo "mobile.hazizz.hu" > build/web/CNAME

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build/web # The folder the action should deploy.