name: Build and Deploy
on:
  push:
    branches: [ web, web-actions ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image:  cirrusci/flutter:beta
    steps:
      - name: Checkout ğŸ›ï¸
      - uses: actions/checkout@v2
        run: flutter pub get

      - name: Build ğŸ”§
        run: |
          flutter config --enable-web
          flutter build web --release

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build/web # The folder the action should deploy.